version: "3"
services:
  valheim:
    image: sethmachineio/valheim-server
    user: "1000:1000"
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    volumes:
      - ./valheim-data:/home/steam/valheim-data
      - ./valheim-server:/home/steam/valheim-server
    environment:
      - VALHEIM_SERVER_NAME=MyServer
      - VALHEIM_WORLD_NAME=NewWorld
      - VALHEIM_PASSWORD=password
