version: "3"
services:
  valheim:
    image: sethmachineio/valheim-server
    user: "1000:1000"
    ports:
      - 2456:2456
      - 2457:2457
      - 2458:2458
    volumes:
      - ./valheim-data:/home/steam/valheim-data
    environment:
      - VALHEIM_SERVER_NAME="MyServer"
      - VALHEIM_WORLD_NAME="NewWorld"
      - VALHEIM_PASSWORD="password"
